version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python migrate.py && uvicorn main:app --host 0.0.0.0 --port ${PORT} --log-level debug"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  pg-data:
    driver: local