version: "3.7"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


  pytest-statistic:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.test
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python migrate.py && pytest tests -x -rfs -vv --color yes"
    depends_on:
      - db