"""initial

Revision ID: 96d221624293
Revises: 
Create Date: 2023-03-29 14:27:49.111521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d221624293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.CheckConstraint('clicks >= 0'),
    sa.CheckConstraint('cost >= 0'),
    sa.CheckConstraint('views >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_id'), 'statistic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_id'), table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###
